name: Build and Package TLA Proof Manager
on: [pull_request]
jobs:
    test:
        name: Build and Test
        runs-on: ${{ matrix.operating-system }}
        strategy:
            fail-fast: false
            matrix:
                operating-system: [
                    macos-latest,
                    ubuntu-latest]
                ocaml-compiler: [
                    '0',
                    '1',
                    '2',
                    ]
                include:
                - operating-system: macos-latest
                  INSTALLER: tlaps-1.5.0-i386-darwin-inst.bin
                  DOWNLOADS: tlaps-1.5.0-i386-darwin-inst
                - operating-system: ubuntu-latest
                  INSTALLER: tlaps-1.5.0-x86_64-linux-gnu-inst.bin
                  DOWNLOADS: tlaps-1.5.0-x86_64-linux-gnu
        steps:
            - uses: actions/checkout@v2
            - name: Get OCaml version
              run: |
                INDEX=${{ matrix.ocaml-compiler }}
                OCAML_VERSION=\
                `python .github/workflows/ocaml_versions.py $INDEX`
                echo "OCAML_VERSION=$OCAML_VERSION" \
                >> $GITHUB_ENV
                echo "OCAML_VERSION = $OCAML_VERSION"
            - uses: ocaml/setup-ocaml@v2
              with:
                ocaml-compiler: ${{ env.OCAML_VERSION }}
            - uses: actions/cache@v2
              id: cache
              with:
                path: ${{ matrix.DOWNLOADS }}
                key: ${{ matrix.DOWNLOADS }}
            - name: Build installer of TLAPS
              run: |
                eval $(opam env)
                ./configure
                cd tools/installer
                ./tlaps-release.sh
            - name: Run installer of TLAPS
              run: |
                cd tools/installer
                ./${{ matrix.INSTALLER }} -d ../..
            - name: Install dependencies for testing
              run: |
                opam install kaputt
            - name: Run a subset of `tlapm` tests
              run: |
                eval $(opam env)
                PATH=$(pwd)/bin:$(pwd)/lib/tlaps/bin:$PATH make test
            - name: Run all `tlapm` tests
              run: |
                eval $(opam env)
                make
                PATH=$(pwd)/bin:$(pwd)/lib/tlaps/bin:$PATH make testall
            - name: Print Test Results
              if: matrix.operating-system == 'ubuntu-latest'
              run: |
                cat test/tests.log
